export type MonitorSelection =
  | 'dateTime'
  | 'patientMode'
  | 'beacon'
  | 'battery'
  | 'hrVital'
  | 'nibpVital'
  | 'etco2Vital'
  | 'spo2Vital'
  | 'spo2Scale'
  | 'spo2Label'
  | 'etco2Scale'
  | 'etco2Label'
  | 'ecgGain'
  | 'padsLabel'
  | 'bottomStatusToggle'
